/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

/**
 * Skill file model + role_list generation (design 5, technical spec 2.2).
 *
 * Skills are file-backed procedural memory. A skill declares the roles it belongs
 * to in YAML frontmatter; the role registry (`role_list.md`) is regenerated by a
 * DETERMINISTIC regex over every skill's `roles:` field -- no LLM. This module is
 * the pure parsing + generation core; the file-backed store wraps it with I/O and
 * a file-watch/pre-dispatch regen (gotcha G5).
 */

/** Cross-transfer hint for the curator (design 5.3). */
export type TransferScope = 'global' | 'repo';

export interface ISkillFrontmatter {
	readonly id: string;
	readonly roles: readonly string[];
	readonly transferScope?: TransferScope;
	/** Monotonic version (design 5.3). */
	readonly version?: number;
	/** What produced/updated the skill, e.g. `session:abc`, `steer:def`. */
	readonly provenance?: readonly string[];
	/** Optional activation hints, e.g. `issue.opened`. */
	readonly triggers?: readonly string[];
}

export interface IParsedSkill {
	readonly frontmatter: ISkillFrontmatter;
	/** The executable instructions (skill body after frontmatter). */
	readonly body: string;
}

/** Framework-owned skills are excluded from role_list and never touched by learning (design 5.1). */
export const FRAMEWORK_SKILL_DIR = '_framework';
export const COORDINATOR_SKILL_DIR = 'coordinator';

/**
 * Parses a `SKILL.md` document into frontmatter + body. Tolerant of missing
 * optional fields; returns `undefined` when there is no `id`. The frontmatter
 * grammar is a minimal YAML subset (scalars + inline `[a, b]` arrays) matching
 * the schema the distiller writes -- we deliberately avoid a full YAML dep.
 */
export function parseSkill(content: string): IParsedSkill | undefined {
	const fm = extractFrontmatterBlock(content);
	if (!fm) {
		return undefined;
	}
	const fields = parseYamlSubset(fm.yaml);
	const id = typeof fields['id'] === 'string' ? (fields['id'] as string) : undefined;
	if (!id) {
		return undefined;
	}
	const frontmatter: ISkillFrontmatter = {
		id,
		roles: toStringArray(fields['roles']),
		transferScope: fields['transfer_scope'] === 'repo' ? 'repo' : fields['transfer_scope'] === 'global' ? 'global' : undefined,
		version: typeof fields['version'] === 'number' ? (fields['version'] as number) : undefined,
		provenance: toStringArray(fields['provenance']),
		triggers: toStringArray(fields['triggers']),
	};
	return { frontmatter, body: fm.body.trim() };
}

/**
 * Regenerates the `role_list.md` catalog from a set of parsed skills: role ->
 * skills[] that declare it. Deterministic (sorted); excludes framework skills.
 * This is the ONLY role registry (design 5.3).
 */
export function generateRoleList(skills: readonly IParsedSkill[]): string {
	const byRole = new Map<string, string[]>();
	for (const skill of skills) {
		for (const role of skill.frontmatter.roles) {
			const list = byRole.get(role) ?? [];
			if (!list.includes(skill.frontmatter.id)) {
				list.push(skill.frontmatter.id);
			}
			byRole.set(role, list);
		}
	}
	const roles = [...byRole.keys()].sort();
	const lines = ['# role_list.md (generated - do not edit)'];
	for (const role of roles) {
		const ids = byRole.get(role)!.slice().sort();
		lines.push(`${role}: [${ids.join(', ')}]`);
	}
	return lines.join('\n') + '\n';
}

/** Parses a generated `role_list.md` back into a role -> skill-ids map. */
export function parseRoleList(content: string): Map<string, string[]> {
	const map = new Map<string, string[]>();
	for (const raw of content.split('\n')) {
		const line = raw.trim();
		if (!line || line.startsWith('#')) {
			continue;
		}
		const match = /^([^:]+):\s*\[(.*)\]\s*$/.exec(line);
		if (!match) {
			continue;
		}
		const role = match[1].trim();
		const ids = match[2].split(',').map(s => s.trim()).filter(s => s.length > 0);
		map.set(role, ids);
	}
	return map;
}

/** All distinct roles declared across a set of skills (excluding empties), sorted. */
export function collectRoles(skills: readonly IParsedSkill[]): string[] {
	const roles = new Set<string>();
	for (const skill of skills) {
		for (const role of skill.frontmatter.roles) {
			if (role) { roles.add(role); }
		}
	}
	return [...roles].sort();
}

// --- minimal frontmatter parsing (no external YAML dependency) ---

function extractFrontmatterBlock(content: string): { yaml: string; body: string } | undefined {
	const normalized = content.replace(/^\uFEFF/, '');
	if (!normalized.startsWith('---')) {
		return undefined;
	}
	const end = normalized.indexOf('\n---', 3);
	if (end === -1) {
		return undefined;
	}
	const yaml = normalized.slice(normalized.indexOf('\n', 3) + 1, end);
	const afterMarker = normalized.indexOf('\n', end + 1);
	const body = afterMarker === -1 ? '' : normalized.slice(afterMarker + 1);
	return { yaml, body };
}

function parseYamlSubset(yaml: string): Record<string, unknown> {
	const out: Record<string, unknown> = {};
	for (const raw of yaml.split('\n')) {
		const line = raw.replace(/\s+$/, '');
		if (!line || line.trimStart().startsWith('#')) {
			continue;
		}
		const colon = line.indexOf(':');
		if (colon === -1) {
			continue;
		}
		const key = line.slice(0, colon).trim();
		const valueRaw = line.slice(colon + 1).trim();
		out[key] = coerceScalarOrArray(valueRaw);
	}
	return out;
}

function coerceScalarOrArray(value: string): unknown {
	if (value.length === 0) {
		return '';
	}
	if (value.startsWith('[') && value.endsWith(']')) {
		return value.slice(1, -1).split(',').map(s => stripQuotes(s.trim())).filter(s => s.length > 0);
	}
	if (/^-?\d+(\.\d+)?$/.test(value)) {
		return Number(value);
	}
	return stripQuotes(value);
}

function stripQuotes(s: string): string {
	if ((s.startsWith('"') && s.endsWith('"')) || (s.startsWith('\'') && s.endsWith('\''))) {
		return s.slice(1, -1);
	}
	return s;
}

function toStringArray(value: unknown): string[] {
	if (Array.isArray(value)) {
		return value.filter(v => typeof v === 'string' && v.length > 0) as string[];
	}
	if (typeof value === 'string' && value.length > 0) {
		return [value];
	}
	return [];
}
